In [1]:
import numpy as np

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])

In [5]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [6]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
print(a[0])

[1 2 3 4]


In [8]:
 a = np.array([1, 2, 3])

In [9]:
a

array([1, 2, 3])

In [10]:
np.zeros(2)

array([0., 0.])

In [11]:
a = np.zeros(4)

In [12]:
a

array([0., 0., 0., 0.])

In [13]:
a = np.zeros(4, dtype=int)

In [14]:
a

array([0, 0, 0, 0])

In [15]:
np.empty(3)

array([ 1.06746868e-311,  1.06746646e-311, -0.00000000e+000])

In [16]:
np.empty(3, dtype=int)

array([       2160580655248,        2160576167072, -9223372036854775808])

In [17]:
np.arange(4)

array([0, 1, 2, 3])

In [18]:
a = np.empty(10)

In [19]:
a

array([nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [28]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [31]:
arr = np.array([1, 2, 3, 7, 8, 9, 10,5, 6, 4])

In [30]:
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arr

array([ 1,  2,  3,  7,  8,  9, 10,  5,  6,  4])

In [33]:
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [35]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])


In [37]:
np.concatenate((x, y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
 array_example = np.array([[[0, 1, 2, 3],                        
                            [4, 5, 6, 7]], 
                                                      
                            [[0, 1, 2, 3],
                             [4, 5, 6, 7]],
                            
                            [[0 ,1 ,2, 3],
                             [4, 5, 6, 7]]
                            ])

In [42]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [43]:
array_example.ndim

3

In [44]:
array_example.size

24

In [45]:
array_example.shape

(3, 2, 4)

In [46]:
a = np.arange(12)

In [47]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [48]:
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
a,rshape(2, 6)

NameError: name 'rshape' is not defined

In [50]:
a.reshape(2, 2, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [51]:
a.reshape(3, 2, 2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [52]:
np.reshape(a, newshape=(2, 6), order='C')   

C:\Users\admin\AppData\Local\Temp\ipykernel_17356\3646454235.py:1: DeprecationWarning: `newshape` keyword argument is deprecated, use `shape=...` or pass shape positionally instead. (deprecated in NumPy 2.1)
  np.reshape(a, newshape=(2, 6), order='C')


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [53]:
np.reshape(a, newshape=(2, 6), order='F')

C:\Users\admin\AppData\Local\Temp\ipykernel_17356\3736244526.py:1: DeprecationWarning: `newshape` keyword argument is deprecated, use `shape=...` or pass shape positionally instead. (deprecated in NumPy 2.1)
  np.reshape(a, newshape=(2, 6), order='F')


array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

np.(a, newshape=(2, 6), order='F')

In [54]:
a = np.array([1, 2, 3, 4, 5, 6])

In [55]:
a.shape

(6,)

In [56]:
a2 = a[np.newaxis, :]

In [57]:
a2

array([[1, 2, 3, 4, 5, 6]])

In [58]:
a2.shape

(1, 6)

In [59]:
row_vector = a[np.newaxis, :]

In [60]:
row_vector.shape

(1, 6)

In [61]:
col_vector = a[:, np.newaxis]

In [62]:
col_vector.shape

(6, 1)

In [63]:
col_vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [64]:
row_vector

array([[1, 2, 3, 4, 5, 6]])

In [65]:
a = np.array([1, 2, 3, 4, 5, 6])

In [66]:
a.shape

(6,)

In [67]:
b = np.expand_dims(a, axis=1)

In [68]:
b.shape

(6, 1)

In [69]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [70]:
c = np.expand_dims(a, axis=0)

In [71]:
c

array([[1, 2, 3, 4, 5, 6]])

In [72]:
c.shape

(1, 6)

In [73]:
b = np.expand_dims(a, axis=6)

AxisError: axis 6 is out of bounds for array of dimension 2

In [74]:
b = np.expand_dims(a, axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [75]:
b = np.expand_dims(a, axis=1)

In [76]:
a

array([1, 2, 3, 4, 5, 6])

In [77]:
data = np.array([1, 2, 3])

In [78]:
data[0]

np.int64(1)

In [79]:
data[1]

np.int64(2)

In [80]:
 a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

_IncompleteInputError: incomplete input (1764068984.py, line 1)

In [81]:
 a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [82]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [84]:
print(a[a < 10])

[1 2 3 4 5 6 7 8 9]


In [85]:
 divisible_by_2 = a[a%2==0]

In [86]:
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [87]:
 c = a[(a > 2) & (a < 11)]

In [88]:
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
five_up = (a > 5) | (a == 5 )

In [90]:
five_up

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [91]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [95]:
b = np.nonzero(a < 12)

In [96]:
b

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2]),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2]))